import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Loader2, Music, Building2, CreditCard, Globe, AlertCircle, ArrowLeft, MapPin } from "lucide-react";
import { PaymentMethodSetup } from "./PaymentMethodSetup";
import { InDashboardPayment } from "./InDashboardPayment";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { detectUserCurrency, wasAutoDetected } from "@/lib/detectCurrency";

interface InitialAccountSetupProps {
  onComplete: () => void;
}

// Combined label access fee + card verification fee
const LABEL_COMBINED_FEE = 9.58; // $7.29 + $2.29 = $9.58 CAD

export const InitialAccountSetup = ({
  onComplete
}: InitialAccountSetupProps) => {
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [labelPaymentData, setLabelPaymentData] = useState<{
    clientSecret: string;
    publishableKey: string;
    paymentIntentId: string;
  } | null>(null);
  const [labelPaymentLoading, setLabelPaymentLoading] = useState(false);
  const [currencyAutoDetected, setCurrencyAutoDetected] = useState(false);
  const [formData, setFormData] = useState(() => {
    // Detect currency on initial render
    const detectedCurrency = detectUserCurrency();
    return {
      fullName: "",
      accountType: "",
      artistName: "",
      labelName: "",
      preferredCurrency: detectedCurrency
    };
  });

  // Check if currency was auto-detected on mount
  useEffect(() => {
    setCurrencyAutoDetected(wasAutoDetected());
  }, []);

  // Total steps: 4 for artist (name, type, artistName, currency), 5 for label (name, type, labelName, payment, currency)
  const isLabelAccount = formData.accountType === "label";
  const totalSteps = isLabelAccount ? 5 : 4;

  // Initialize label payment when user selects label account and reaches step 4
  useEffect(() => {
    if (isLabelAccount && step === 4 && !labelPaymentData && !labelPaymentLoading) {
      initializeLabelPayment();
    }
  }, [step, isLabelAccount]);

  const initializeLabelPayment = async () => {
    setLabelPaymentLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke('create-label-access-payment');
      if (error) throw error;
      setLabelPaymentData(data);
    } catch (error: any) {
      console.error("Error initializing label payment:", error);
      toast.error("Failed to initialize payment. Please try again.");
    } finally {
      setLabelPaymentLoading(false);
    }
  };

  const handleNext = () => {
    if (step === 1 && !formData.fullName.trim()) {
      toast.error("Please enter your full name");
      return;
    }
    if (step === 2 && !formData.accountType) {
      toast.error("Please select an account type");
      return;
    }
    if (step === 3) {
      if (formData.accountType === "artist" && !formData.artistName.trim()) {
        toast.error("Please enter your artist name");
        return;
      }
      if (formData.accountType === "label" && !formData.labelName.trim()) {
        toast.error("Please enter your label name");
        return;
      }
    }
    if (step < totalSteps) {
      setStep(step + 1);
    }
  };

  const handleComplete = async () => {
    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("User not authenticated");
      const isArtist = formData.accountType === "artist";

      const profileUpdate: any = {
        full_name: formData.fullName,
        account_type: isArtist ? "artist" : "label",
        onboarding_completed: false, // Will be set to true after tutorial
        preferred_currency: formData.preferredCurrency
      };
      if (isArtist) {
        profileUpdate.artist_name = formData.artistName;
      } else {
        profileUpdate.label_name = formData.labelName;
      }

      const { error: profileError } = await supabase.from("profiles").update(profileUpdate).eq("id", user.id);
      if (profileError) throw profileError;

      // Create label entry for label accounts
      if (!isArtist && formData.labelName.trim()) {
        const { data: newLabel, error: labelError } = await supabase
          .from("labels")
          .insert({
            name: formData.labelName.trim(),
            user_id: user.id,
            label_id: '' // Will be auto-generated by trigger
          })
          .select()
          .single();

        if (labelError) {
          console.error('Error creating label:', labelError);
          throw labelError;
        }

        if (newLabel) {
          // Update profile with active_label_id
          await supabase.from("profiles").update({ active_label_id: newLabel.id }).eq("id", user.id);

          const { error: membershipError } = await supabase
            .from("user_label_memberships")
            .insert({
              user_id: user.id,
              label_id: newLabel.id,
              label_name: formData.labelName.trim(),
              role: "owner"
            });
          if (membershipError) {
            console.error('Error creating membership:', membershipError);
          }
        }
      }

      toast.success("Account setup complete!");
      onComplete();
    } catch (error: any) {
      console.error("Error completing account setup:", error);
      toast.error(error.message || "Failed to complete account setup");
    } finally {
      setLoading(false);
    }
  };

  const handleLabelPaymentSuccess = () => {
    toast.success("Payment successful!");
    setStep(step + 1);
  };

  // Get step content based on account type
  const getStepContent = () => {
    // Step 1: Full Name
    if (step === 1) {
      return (
        <div className="space-y-4 animate-fade-in">
          <div className="space-y-2">
            <Label htmlFor="fullName">What's your full name?</Label>
            <Input
              id="fullName"
              placeholder="John Doe"
              value={formData.fullName}
              onChange={e => setFormData({ ...formData, fullName: e.target.value })}
              className="bg-background/50 border-border"
              autoFocus
            />
          </div>
        </div>
      );
    }

    // Step 2: Account Type
    if (step === 2) {
      return (
        <div className="space-y-4 animate-fade-in">
          <div className="space-y-4">
            <Label>Are you an artist or a label?</Label>
            <RadioGroup
              value={formData.accountType}
              onValueChange={value => setFormData({ ...formData, accountType: value })}
              className="space-y-3"
            >
              <div
                className={`flex items-center space-x-3 border rounded-lg p-4 cursor-pointer transition-all ${
                  formData.accountType === "artist" ? "border-primary bg-primary/5" : "border-border hover:border-primary/50"
                }`}
                onClick={() => setFormData({ ...formData, accountType: "artist" })}
              >
                <RadioGroupItem value="artist" id="artist" />
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <Music className="h-5 w-5 text-primary" />
                    <Label htmlFor="artist" className="text-base font-medium cursor-pointer">
                      Artist Account
                    </Label>
                    <span className="text-xs bg-green-500/20 text-green-500 px-2 py-0.5 rounded">
                      FREE
                    </span>
                  </div>
                  <p className="text-sm text-muted-foreground mt-1">
                    Release music under up to 3 artist names with 1 label
                  </p>
                </div>
              </div>

              <div
                className={`flex items-center space-x-3 border rounded-lg p-4 cursor-pointer transition-all ${
                  formData.accountType === "label" ? "border-primary bg-primary/5" : "border-border hover:border-primary/50"
                }`}
                onClick={() => setFormData({ ...formData, accountType: "label" })}
              >
                <RadioGroupItem value="label" id="label" />
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <Building2 className="h-5 w-5 text-primary" />
                    <Label htmlFor="label" className="text-base font-medium cursor-pointer">
                      Label Account
                    </Label>
                    <span className="text-xs bg-primary/20 text-primary px-2 py-0.5 rounded">
                      ${LABEL_COMBINED_FEE.toFixed(2)} CAD
                    </span>
                  </div>
                  <p className="text-sm text-muted-foreground mt-1">
                    Full access to manage unlimited artists and labels
                  </p>
                </div>
              </div>
            </RadioGroup>
          </div>
        </div>
      );
    }

    // Step 3: Artist/Label Name
    if (step === 3) {
      return (
        <div className="space-y-4 animate-fade-in">
          <div className="space-y-2">
            {formData.accountType === "artist" ? (
              <>
                <Label htmlFor="artistName">What's your artist name?</Label>
                <Input
                  id="artistName"
                  placeholder="Your Artist Name"
                  value={formData.artistName}
                  onChange={e => setFormData({ ...formData, artistName: e.target.value })}
                  className="bg-background/50 border-border"
                  autoFocus
                />
                <p className="text-xs text-muted-foreground">
                  This is how you'll be credited on your releases. You can add up to 3 artist names total.
                </p>
              </>
            ) : (
              <>
                <Label htmlFor="labelName">What's your label name?</Label>
                <Input
                  id="labelName"
                  placeholder="Your Label Name"
                  value={formData.labelName}
                  onChange={e => setFormData({ ...formData, labelName: e.target.value })}
                  className="bg-background/50 border-border"
                  autoFocus
                />
                <p className="text-xs text-muted-foreground">
                  This is your official label name for all releases
                </p>
              </>
            )}
          </div>

          <div className="p-3 bg-muted rounded-md">
            <p className="text-sm font-medium mb-2">Distribution Pricing</p>
            <div className="text-sm text-muted-foreground space-y-1">
              <p>• Trackball Eco: $1 CAD/track + $4 CAD UPC</p>
              <p>• Trackball Standard: $5 CAD/track + $8 CAD UPC</p>
            </div>
          </div>
        </div>
      );
    }

    // Step 4 for Label: Combined Payment (Access Fee + Card Verification)
    if (isLabelAccount && step === 4) {
      const handleSwitchToArtist = () => {
        setFormData(prev => ({ ...prev, accountType: "artist", labelName: "", artistName: "" }));
        setLabelPaymentData(null);
        setStep(2);
        toast.info("Switched to Artist Account");
      };

      return (
        <div className="space-y-4 animate-fade-in">
          <Alert className="border-primary/30 bg-primary/5">
            <CreditCard className="h-4 w-4 text-primary" />
            <AlertDescription className="text-sm">
              A one-time fee of <span className="font-semibold">${LABEL_COMBINED_FEE.toFixed(2)} CAD</span> is required.
              <br />
              <span className="text-xs text-muted-foreground">
                Includes $7.29 label access + $2.29 card verification
              </span>
            </AlertDescription>
          </Alert>

          {labelPaymentLoading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="w-8 h-8 animate-spin text-primary" />
            </div>
          ) : labelPaymentData ? (
            <InDashboardPayment
              clientSecret={labelPaymentData.clientSecret}
              publishableKey={labelPaymentData.publishableKey}
              description="Label Account Access + Card Verification"
              amount={958}
              onSuccess={handleLabelPaymentSuccess}
              onCancel={() => setStep(3)}
            />
          ) : (
            <div className="text-center py-8">
              <p className="text-sm text-muted-foreground mb-4">Failed to load payment form.</p>
              <Button onClick={initializeLabelPayment}>Try Again</Button>
            </div>
          )}

          {/* Switch to Artist Account Option */}
          <div className="pt-4 border-t border-border">
            <p className="text-sm text-muted-foreground text-center mb-3">
              Don't want to pay the label fee?
            </p>
            <Button
              variant="outline"
              onClick={handleSwitchToArtist}
              className="w-full"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Switch to Artist Account (Free)
            </Button>
          </div>
        </div>
      );
    }

    // Step 4 for Artist / Step 5 for Label: Currency Selection
    const currencyStep = isLabelAccount ? 5 : 4;
    if (step === currencyStep) {
      return (
        <div className="space-y-4 animate-fade-in">
          <div className="flex items-center gap-2 mb-2">
            <Globe className="w-5 h-5 text-primary" />
            <h3 className="font-medium">Display Currency</h3>
          </div>
          <p className="text-sm text-muted-foreground">
            Choose your preferred currency for displaying financial information. All payments will still be processed in CAD.
          </p>
          
          {currencyAutoDetected && (
            <div className="flex items-center gap-2 text-xs text-muted-foreground bg-muted/50 px-3 py-2 rounded-md">
              <MapPin className="w-3 h-3" />
              <span>Auto-detected based on your device settings</span>
            </div>
          )}
          
          <div className="space-y-2">
            <Label>Preferred Display Currency</Label>
            <RadioGroup 
              value={formData.preferredCurrency} 
              onValueChange={(value) => setFormData(prev => ({ ...prev, preferredCurrency: value }))}
              className="grid grid-cols-2 gap-2"
            >
              {[
                { code: "CAD", name: "Canadian Dollar", symbol: "$" },
                { code: "USD", name: "US Dollar", symbol: "$" },
                { code: "EUR", name: "Euro", symbol: "€" },
                { code: "GBP", name: "British Pound", symbol: "£" },
                { code: "AUD", name: "Australian Dollar", symbol: "$" },
                { code: "JPY", name: "Japanese Yen", symbol: "¥" },
              ].map((currency) => (
                <div 
                  key={currency.code}
                  className={`flex items-center space-x-2 border rounded-lg p-3 cursor-pointer transition-all ${
                    formData.preferredCurrency === currency.code 
                      ? "border-primary bg-primary/5" 
                      : "border-border hover:border-primary/50"
                  }`}
                  onClick={() => setFormData(prev => ({ ...prev, preferredCurrency: currency.code }))}
                >
                  <RadioGroupItem value={currency.code} id={`currency-${currency.code}`} />
                  <Label htmlFor={`currency-${currency.code}`} className="cursor-pointer flex-1">
                    <span className="font-mono mr-1">{currency.symbol}</span>
                    <span>{currency.code}</span>
                  </Label>
                </div>
              ))}
            </RadioGroup>
          </div>
        </div>
      );
    }

    return null;
  };

  const showNavigationButtons = () => {
    // Don't show navigation buttons during label payment step (step 4 for labels)
    if (isLabelAccount && step === 4) return false;
    return true;
  };

  const showBackButton = () => {
    // Don't show back during label payment
    if (isLabelAccount && step === 4 && labelPaymentData) return false;
    return step > 1;
  };

  // Check if this is the final step
  const isFinalStep = step === totalSteps;

  return (
    <div className="fixed inset-0 z-[200] bg-background/95 flex items-center justify-center p-4">
      <Card className="w-full max-w-lg border-border animate-fade-in">
        <CardHeader>
          <CardTitle className="text-2xl">Welcome to My Trackball</CardTitle>
          <CardDescription>
            Let's set up your account in just a few steps
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Progress indicator */}
          <div className="flex items-center gap-2">
            {Array.from({ length: totalSteps }).map((_, i) => (
              <div
                key={i}
                className={`h-2 rounded-full transition-all flex-1 ${
                  i + 1 === step ? "bg-primary" : i + 1 < step ? "bg-primary/50" : "bg-muted"
                }`}
              />
            ))}
          </div>

          {getStepContent()}

          {/* Navigation buttons */}
          {showNavigationButtons() && (
            <div className="flex gap-3 pt-4">
              {showBackButton() && (
                <Button
                  variant="outline"
                  onClick={() => setStep(step - 1)}
                  disabled={loading}
                  className="flex-1"
                >
                  Back
                </Button>
              )}
              
              {isFinalStep ? (
                <Button
                  onClick={handleComplete}
                  disabled={loading}
                  className="flex-1"
                >
                  {loading ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Setting up...
                    </>
                  ) : (
                    "Complete Setup"
                  )}
                </Button>
              ) : (
                <Button
                  onClick={handleNext}
                  disabled={loading}
                  className="flex-1"
                >
                  Continue
                </Button>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default InitialAccountSetup;
